const weatherTranslations = {
    "clear sky": "ท้องฟ้าแจ่มใส",
    "few clouds": "เมฆเล็กน้อย",
    "scattered clouds": "เมฆกระจาย",
    "broken clouds": "เมฆแตกกระจาย",
    "overcast clouds": "เมฆครึ้ม",
    "shower rain": "ฝนตกปรอยๆ",
    "rain": "ฝนตก",
    "light rain": "ฝนตกเล็กน้อย",
    "moderate rain": "ฝนตกปานกลาง",
    "heavy intensity rain": "ฝนตกหนัก",
    "very heavy rain": "ฝนตกหนักมาก",
    "extreme rain": "ฝนตกอย่างหนักมาก",
    "freezing rain": "ฝนเยือกแข็ง",
    "light intensity shower rain": "ฝนตกปรอยๆ เบาๆ",
    "heavy intensity shower rain": "ฝนตกปรอยๆ หนัก",
    "ragged shower rain": "ฝนตกปรอยๆ ไม่สม่ำเสมอ",
    "thunderstorm": "พายุฝนฟ้าคะนอง",
    "thunderstorm with light rain": "พายุฝนฟ้าคะนองพร้อมฝนตกเบาๆ",
    "thunderstorm with rain": "พายุฝนฟ้าคะนองพร้อมฝนตก",
    "thunderstorm with heavy rain": "พายุฝนฟ้าคะนองพร้อมฝนตกหนัก",
    "light thunderstorm": "พายุฝนฟ้าคะนองเบาๆ",
    "heavy thunderstorm": "พายุฝนฟ้าคะนองหนัก",
    "ragged thunderstorm": "พายุฝนฟ้าคะนองไม่สม่ำเสมอ",
    "thunderstorm with drizzle": "พายุฝนฟ้าคะนองพร้อมฝนปรอยๆ",
    "light intensity drizzle": "ฝนปรอยๆ เบาๆ",
    "drizzle": "ฝนปรอยๆ",
    "heavy intensity drizzle": "ฝนปรอยๆ หนัก",
    "light intensity drizzle rain": "ฝนตกปรอยๆ เบาๆ",
    "drizzle rain": "ฝนตกปรอยๆ",
    "heavy intensity drizzle rain": "ฝนตกปรอยๆ หนัก",
    "shower drizzle": "ฝนปรอยๆ รุนแรง",
    "snow": "หิมะตก",
    "light snow": "หิมะตกเล็กน้อย",
    "heavy snow": "หิมะตกหนัก",
    "sleet": "หิมะละลาย",
    "light shower sleet": "หิมะละลายเบาๆ",
    "shower sleet": "หิมะละลาย",
    "light rain and snow": "ฝนตกและหิมะตกเล็กน้อย",
    "rain and snow": "ฝนตกและหิมะตก",
    "light shower snow": "หิมะตกปรอยๆ เบาๆ",
    "shower snow": "หิมะตกปรอยๆ",
    "heavy shower snow": "หิมะตกปรอยๆ หนัก",
    "mist": "หมอก",
    "smoke": "ควัน",
    "haze": "หมอกควัน",
    "sand/dust whirls": "พายุทราย/ฝุ่น",
    "fog": "หมอก",
    "sand": "ทราย",
    "dust": "ฝุ่น",
    "volcanic ash": "เถ้าภูเขาไฟ",
    "squalls": "พายุฝน",
    "tornado": "พายุทอร์นาโด"
  };
  
  export default weatherTranslations;
  